# Generated by Django 4.0.3 on 2022-04-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
