# Generated by Django 3.2 on 2022-05-04 09:57

import CRM.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(default=CRM.models.getDefaultTeacher, on_delete=django.db.models.deletion.PROTECT, to='CRM.teacher'),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
