# Generated by Django 3.2 on 2022-07-03 10:01

import CRM.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_auto_20220701_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField(default=0)),
                ('note', models.CharField(default='', max_length=200)),
                ('teacher', models.ForeignKey(default=CRM.models.getDefaultTeacher, on_delete=django.db.models.deletion.PROTECT, to='CRM.teacher')),
            ],
        ),
    ]
